# set up the default terminal
ENV["TERM"]="linux"

Vagrant.require_version ">= 2.2.10"
Vagrant.configure("2") do |config|
  config.vm.box = "opensuse/Leap-15.6.x86_64"
  config.vm.box_version = "15.6.13.356"
  config.vm.boot_timeout = 900

  # st the static IP for the vagrant box
  config.vm.network "private_network", ip: "192.168.50.4"
  
  # consifure the parameters for VirtualBox provider
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 4
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
  end
end
