# set up the default terminal
ENV["TERM"]="linux"

Vagrant.configure("2") do |config|
  
  # Use any version shown here https://app.vagrantup.com/opensuse/boxes/Leap-15.4.x86_64
  config.vm.box = "opensuse/Leap-15.6.x86_64"
  config.vm.box_version = "15.6.13.356"

  # st the static IP for the vagrant box
  config.vm.network "private_network", ip: "192.168.50.4"
  
  # consifure the parameters for VirtualBox provider
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 4
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
  end
end
